#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

. "$(dirname $0)"/lib

PKG_NAME="__PKG_NAME__"
ETC_PATH="/usr/syno/etc/packages/$PKG_NAME/"
TARGET_PATH="/var/packages/$PKG_NAME/target"
SHARE_PATH="$(synoshare --get docker | grep $'\t Path' | sed 's/.*\[\(.*\)].*/\1/')"

GITEA_NAME=synology_gitea
GITEA_PROFILE="$TARGET_PATH"/config/synology_gitea
GITEA_PACKAGE_NAME="__GITEA_PACKAGE_NAME__"
GITEA_PACKAGE_NAME_ESCAPED="__GITEA_PACKAGE_NAME_ESCAPED__"
GITEA_VERSION="__GITEA_VERSION__"
GITEA_SIZE="__GITEA_SIZE__"

MARIADB_NAME=synology_gitea_db
MARIADB_PROFILE="$TARGET_PATH"/config/synology_gitea_db
MARIADB_PACKAGE_NAME="__MARIADB_PACKAGE_NAME__"
MARIADB_PACKAGE_NAME_ESCAPED="__MARIADB_PACKAGE_NAME_ESCAPED__"
MARIADB_VERSION="__MARIADB_VERSION__"
MARIADB_SIZE="__MARIADB_SIZE__"
MARIADB_SHARE="__MARIADB_SHARE__"

SYNO_WEBAPI=/usr/syno/bin/synowebapi
DOCKER_BIN=/usr/local/bin/docker
DOCKER_GITEA_CONFIG_CUSTOM="$ETC_PATH"/config_custom
DOCKER_GITEA_CONFIG_CONTAINER_PORTS="$ETC_PATH"/config_container_ports
DOCKER_GITEA_CONFIG_FILE=/tmp/"$GITEA_NAME".config


if [ "$SYNOPKG_TEMP_LOGFILE" ]; then
	log() {
		local text="$1"
		local idx=0
		shift 1
		for val in "$@"; do
			text="${text//\{$idx\}/$val}"
			let idx=1+$idx
		done
		echo "$text" >> $SYNOPKG_TEMP_LOGFILE
	}
fi

quote_sed() {
	sed -e 's|\\|\\\\|g' -e 's|&|\\\&|g' -e 's|/|\\/|g'
}

quote_sql() {
	sed -e "s|\`|\`\`|g"
}

quote_sh() {
	sed -e 's|\\|\\\\|g' -e 's|\"|\\\"|g' -e 's|`|\\`|g' -e 's|\\$|\\$|g'
}

quote_json() {
	sed -e 's|\\|\\\\|g' -e 's|\"|\\\"|g'
}

DBAdminCheck()
{
	local user="$1"
	local password="$2"
	local mysql="$3"

	# Check admin's account and password
	if ! $mysql -u "$user" --password="$password" -e "exit"; then
		log "$wizard_admin_info_error"
		return 1
	fi

	# Check whether the account have all privileges *.* or not
	$mysql -u "$user" --password="$password" -e "SHOW GRANTS FOR ${user}@localhost" | grep -q "GRANT ALL PRIVILEGES ON \*\.\* TO '${user}'@'localhost'.* WITH GRANT OPTION.*"
	if [ $? -eq 1 ]; then
		log "$db_admin_permission_error"
		return 1
	fi
	return 0
}


#=======================================================================================================================
# stringInArray
#=======================================================================================================================
stringInArray() {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 1; done
  return 0
}

#=======================================================================================================================
# BackupCustomEnvironmentVariablesOld
#=======================================================================================================================
BackupCustomEnvironmentVariables()
{
    $SYNO_WEBAPI --exec api=SYNO.Docker.Container.Profile version=1 method=export outfile="$DOCKER_GITEA_CONFIG_FILE" name="$GITEA_NAME"
    if ! [ -s "$DOCKER_GITEA_CONFIG_FILE" ]; then
      return 0
    fi

    env_ignore_file=$(cd `dirname $0` && pwd)/env_ignore
    declare -A env_ignore_variables; declare -a keys;  declare -a values;

    i=0
    while read line;
    do
        env_ignore_variables[$i]=$(echo "$line" | tr -d '\r')
        (( i++ ))
    done < $env_ignore_file

    # Rewrite File from new
    if [ -f "$DOCKER_GITEA_CONFIG_CUSTOM" ]; then
        rm "$DOCKER_GITEA_CONFIG_CUSTOM"
    fi

    i=0
    tmp_keys=$(jq '.env_variables[] | .key' <"$DOCKER_GITEA_CONFIG_FILE" | tr -d '"')
    while read line
    do
        keys[$i]="$line"
        (( i++ ))
    done <<< "${tmp_keys[@]}"

    i=0
    tmp_values=$(jq '.env_variables[] | .value' <"$DOCKER_GITEA_CONFIG_FILE" | tr -d '"')
    while read line
    do
        values[$i]="$line"
        (( i++ ))
    done <<< "${tmp_values[@]}"

    for i in "${!keys[@]}"
    do
        stringInArray "${keys[$i]}" "${env_ignore_variables[@]}"
        if [ $? == 0 ]; then
            echo "${keys[$i]}=${values[$i]}" >> "$DOCKER_GITEA_CONFIG_CUSTOM"
        fi
    done

    rm $DOCKER_GITEA_CONFIG_FILE
    return 1
}

#=======================================================================================================================
# RestoreCustomEnvironmentVariables
#=======================================================================================================================
RestoreCustomEnvironmentVariables()
{
    declare -a keys

    # if file exists and has a size greater than zero
    if ! [ -s $DOCKER_GITEA_CONFIG_CUSTOM ]
    then
        return 0
    fi

    cp $GITEA_PROFILE $GITEA_PROFILE"_backup"
    chmod 0644 $GITEA_PROFILE"_backup"

    i=0
    tmp_keys=$(jq '.env_variables[].key' <"$GITEA_PROFILE" | tr -d '"')
    while read line
    do
        keys[$i]="$line"
        (( i++ ))
    done <<< "${tmp_keys[@]}"

    while read LINE;
    do
        key=$(echo $LINE | cut -f1 -d=)
        value=$(echo $LINE | cut -f2 -d=)
        value=$(echo "$value" | tr -d '\r') # trim \r on line-end
        stringInArray "$key" "${keys[@]}"
        if [ $? == 1 ]; then
            index=$(echo ${keys[@]/$key//} | cut -d/ -f1 | wc -w | tr -d ' ')
             #echo "$key:$value:$index"
            jq -c ".env_variables[$index].value=\"$value\""  <$GITEA_PROFILE >$GITEA_PROFILE".out" && mv $GITEA_PROFILE".out" $GITEA_PROFILE
        else
            jq -c ".env_variables += [{\"key\" : \"$key\", \"value\" : \"$value\"}]"  <$GITEA_PROFILE >$GITEA_PROFILE".out" && mv $GITEA_PROFILE".out" $GITEA_PROFILE
        fi
    done < $DOCKER_GITEA_CONFIG_CUSTOM
}

#=======================================================================================================================
# BackupContainerPorts
#=======================================================================================================================
BackupContainerPorts()
{
    declare -a container_ports;  declare -a host_ports; declare -a types;

    $SYNO_WEBAPI --exec api=SYNO.Docker.Container.Profile version=1 method=export outfile="$DOCKER_GITEA_CONFIG_FILE" name="$GITEA_NAME"
    if ! [ -s "$DOCKER_GITEA_CONFIG_FILE" ]; then
      return 0
    fi

    # Rewrite File from new
    if [ -f "$DOCKER_GITEA_CONFIG_CONTAINER_PORTS" ]; then
        rm "$DOCKER_GITEA_CONFIG_CONTAINER_PORTS"
    fi

    i=0
    tmp_container_ports=$(jq '.port_bindings[].container_port' <"$DOCKER_GITEA_CONFIG_FILE" | tr -d '"')
    while read line
    do
        container_ports[$i]="$line"
        (( i++ ))
    done <<< "${tmp_container_ports[@]}"

    i=0
    tmp_host_ports=$(jq '.port_bindings[].host_port' <"$DOCKER_GITEA_CONFIG_FILE" | tr -d '"')
    while read line
    do
        host_ports[$i]="$line"
        (( i++ ))
    done <<< "${tmp_host_ports[@]}"

    i=0
    tmp_types=$(jq '.port_bindings[].type' <"$DOCKER_GITEA_CONFIG_FILE" | tr -d '"')
    while read line
    do
        types[$i]="$line"
        (( i++ ))
    done <<< "${tmp_types[@]}"

    for i in "${!container_ports[@]}"
    do
        echo "${container_ports[$i]}:${host_ports[$i]}:${types[$i]}" >> "$DOCKER_GITEA_CONFIG_CONTAINER_PORTS"
    done

    rm $DOCKER_GITEA_CONFIG_FILE
    return 1
}

#=======================================================================================================================
# BackupContainerPorts
#=======================================================================================================================
RestoreContainerPorts()
{
    # if file exists and has a size greater than zero
    if ! [ -s $DOCKER_GITEA_CONFIG_CONTAINER_PORTS ]
    then
        return 0
    fi

    cp $GITEA_PROFILE $GITEA_PROFILE"_backup_ports"
    chmod 0644 $GITEA_PROFILE"_backup_ports"

    json_content=""
    while read LINE;
    do
        container_port=$(echo $LINE | cut -f1 -d: | tr -d '\r')
        host_port=$(echo $LINE | cut -f2 -d: | tr -d '\r')
        type=$(echo $LINE | cut -f3 -d: | tr -d '\r')
        json_content="$json_content{\"container_port\" : $container_port, \"host_port\" : \"$host_port\", \"type\" : \"$type\"},"
    done < $DOCKER_GITEA_CONFIG_CONTAINER_PORTS

    jq -c ".port_bindings=[${json_content::-1}]" < $GITEA_PROFILE > $GITEA_PROFILE".out" && mv $GITEA_PROFILE".out" $GITEA_PROFILE
}
