#!/bin/sh
. "$(dirname $0)"/common
. "$(dirname $0)"/ini_val
. "$ETC_PATH"/config

########################################################################################################################
# VARIABLES
########################################################################################################################
FORCE_RENEW=0
SYNO_CERT_DIR="/usr/syno/etc/certificate/_archive"
GITEA_SHARE="$SHARE_PATH/$SHARE"
GITEA_CERT_DIR="$GITEA_SHARE/certs"
GITEA_CONFIG="$GITEA_SHARE/gitea/conf/app.ini"
HOSTNAME=$(ini_val ${GITEA_CONFIG} server.DOMAIN)

########################################################################################################################
# PARAMETER HANDLING
########################################################################################################################
for i in "$@"
do
    case $i in
        --force-renew)
            FORCE_RENEW=1
        ;;
        *)
            # unknown option
        ;;
    esac
    shift
done

if [ $FORCE_RENEW = 1 ] && [ -d "$GITEA_CERT_DIR" ]; then
  rm -rf "$GITEA_CERT_DIR"
fi

if ! [ -d "$GITEA_CERT_DIR" ]; then
  mkdir -p "$GITEA_CERT_DIR"
fi

if ! [ -f "$GITEA_CERT_DIR/gitea.key" ]; then
  openssl genrsa -out "$GITEA_CERT_DIR/gitea.key" 2048
fi

if ! [ -f "$GITEA_CERT_DIR/gitea.csr" ]; then
  openssl req -new -key "$GITEA_CERT_DIR/gitea.key" -subj "/C=DE/ST=Germany/L=Duisburg/O=jboxberger/CN=$HOSTNAME" -out "$GITEA_CERT_DIR/gitea.csr"
fi

if ! [ -f "$GITEA_CERT_DIR/gitea.crt" ]; then
  openssl x509 -req -days 3650 -in "$GITEA_CERT_DIR/gitea.csr" -signkey "$GITEA_CERT_DIR/gitea.key" -out "$GITEA_CERT_DIR/gitea.crt"
fi
chmod 400 "$GITEA_CERT_DIR/gitea.key"

if ! [ -f "$GITEA_CERT_DIR/dhparam.pem" ] && [ -f "/usr/syno/etc/ssl/dh2048.pem" ]; then
  cp "/usr/syno/etc/ssl/dh2048.pem" "$GITEA_CERT_DIR/dhparam.pem"
fi

ini_val ${GITEA_CONFIG} server.PROTOCOL https
ini_val ${GITEA_CONFIG} server.CERT_FILE "//data/gitea/certs/gitea.crt"
ini_val ${GITEA_CONFIG} server.KEY_FILE "/data/gitea/certs/gitea.key"
